In [1]:
# import the dependencies.
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from citipy import citipy
%matplotlib qt

In [2]:
# create random latitudes and longitudes

lats = np.random.uniform(low= -90.000, high= 90.000, size=1500)
lngs = np.random.uniform(low= -180.000, high= 180.000, size=1500)
lat_lngs = zip(lats, lngs)
lat_lngs

In [3]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [4]:
#for coordidate in coordinates:
 #   print(coordidate[0], coordidate[1])

In [5]:
# create list to hold cities name

cities = []

# identify nearest city name for each latitude and longitude

for coordinate in coordinates:
    
    city = citipy.nearest_city(coordinate[0],coordinate[1]).city_name
    
    # if the city is unique, then we will add the city name
    
    if city not in cities:
        cities.append(city)

# print the cities count to confirm the total cities.
    
len(cities)

596

In [6]:
# import the request library

import requests

# import API key for weather

from config import weather_api_key

In [7]:
# starting URL in for API call.

url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
print(url)

http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=b05f7fd70b27a65f0aff26106c1f0dca

In [8]:
# import the time library and the datetime module from the datetime library

import time
from datetime import datetime

In [9]:
# create an empty list.

city_data = []

# print beginning.

print("Beginning Data Retrieval")
print("_________________________")

# create the counters.

record_count = 1

set_count = 1

# loop to retrive the cities data

#for i in range(len(cities)):
 
for i, city in enumerate(cities):
    
    # group the cities in set of 50 for logging purpose
    if (i % 50 == 0 and i >=50):
        
        set_count +=1
        record_count = 1
        time.sleep(60)
        
    # creat endpoint URL with each city
    
    city_url= url +"&q="+ city.replace(" ","+")
    
    
    #log the URL, record and set numbers and the city
    
    print(f"Processing Record {record_count} of set {set_count} | {city}")
          
    # Add 1 to the record count.
          
    record_count +=1
          
    # run an API request for each city
          
    try:
        # parse the JSON and retrive data.
          
        city_weather = requests.get(city_url).json()
          
        # parse out the needed data
          
        city_lat = city_weather['coord']['lat']
        city_lng = city_weather['coord']['lon']
        city_max_temp = city_weather['main']['temp_max']
        city_humidity = city_weather['main']['humidity']
        city_cloud = city_weather['clouds']['all']
        city_wind = city_weather['wind']['speed']
        city_country = city_weather['sys']['country']
          
        #convert date in to the ISO format
          
        city_date = datetime.utcfromtimestamp(city_weather['dt']).strftime('%Y-%m-%d %H:%M:%S')
          
        #append the city information in to list
        city_data.append({"City": city.title(),
                         "Lat": city_lat,
                         "Lng": city_lng,
                         "Max Temp": city_max_temp,
                         "Humidity": city_humidity,
                         "Clouldiness" : city_cloud,
                         "Wind Speed": city_wind,
                         "Country": city_country,
                         "Date": city_date})
          
        # if an error is experienced, skip the city.
          
    except:
        print(f"City not found {city}")
        pass
          
# indicate theat data loading is completed.
          
print("________________________")

print("Data Retrieval Completed")
          
print("________________________")

Beginning Data Retrieval
_________________________
Processing Record 1 of set 1 | bredasdorp
Processing Record 2 of set 1 | hami
Processing Record 3 of set 1 | busselton
Processing Record 4 of set 1 | buraydah
Processing Record 5 of set 1 | nome
Processing Record 6 of set 1 | kazalinsk
City not found kazalinsk
Processing Record 7 of set 1 | yellowknife
Processing Record 8 of set 1 | vuktyl
Processing Record 9 of set 1 | nikolskoye
Processing Record 10 of set 1 | carnarvon
Processing Record 11 of set 1 | esperance
Processing Record 12 of set 1 | puerto ayora
Processing Record 13 of set 1 | kapaa
Processing Record 14 of set 1 | atuona
Processing Record 15 of set 1 | tromso
Processing Record 16 of set 1 | jamestown
Processing Record 17 of set 1 | ushuaia
Processing Record 18 of set 1 | cape town
Processing Record 19 of set 1 | felanitx
Processing Record 20 of set 1 | mataura
Processing Record 21 of set 1 | mahebourg
Processing Record 22 of set 1 | ponta do sol
Processing Record 23 of set 1 | ushumun
Processing Record 24 of set 1 | hobart
Processing Record 25 of set 1 | torbay
Processing Record 26 of set 1 | gedo
Processing Record 27 of set 1 | brae
Processing Record 28 of set 1 | rikitea
Processing Record 29 of set 1 | mnogovershinnyy
Processing Record 30 of set 1 | nantucket
Processing Record 31 of set 1 | vao
Processing Record 32 of set 1 | punta arenas
Processing Record 33 of set 1 | tsihombe
City not found tsihombe
Processing Record 34 of set 1 | theodoriana
Processing Record 35 of set 1 | hithadhoo
Processing Record 36 of set 1 | iqaluit
Processing Record 37 of set 1 | arraial do cabo
Processing Record 38 of set 1 | ocampo
Processing Record 39 of set 1 | awjilah
Processing Record 40 of set 1 | dikson
Processing Record 41 of set 1 | vaini
Processing Record 42 of set 1 | rocha
Processing Record 43 of set 1 | qui nhon
Processing Record 44 of set 1 | belushya guba
City not found belushya guba
Processing Record 45 of set 1 | hermanus
Processing Record 46 of set 1 | bluff
Processing Record 47 of set 1 | albany
Processing Record 48 of set 1 | buenos aires
Processing Record 49 of set 1 | sansai
City not found sansai
Processing Record 50 of set 1 | westport
Processing Record 1 of set 2 | kruisfontein
Processing Record 2 of set 2 | sentyabrskiy
City not found sentyabrskiy
Processing Record 3 of set 2 | port hardy
Processing Record 4 of set 2 | mar del plata
Processing Record 5 of set 2 | smithers
Processing Record 6 of set 2 | mount gambier
Processing Record 7 of set 2 | qaanaaq
Processing Record 8 of set 2 | sabang
Processing Record 9 of set 2 | ahipara
Processing Record 10 of set 2 | yamethin
Processing Record 11 of set 2 | tomatlan
Processing Record 12 of set 2 | gat
Processing Record 13 of set 2 | kaitangata
Processing Record 14 of set 2 | bambous virieux
Processing Record 15 of set 2 | jinchang
Processing Record 16 of set 2 | hasaki
Processing Record 17 of set 2 | broome
Processing Record 18 of set 2 | sur
Processing Record 19 of set 2 | puerto escondido
Processing Record 20 of set 2 | port alfred
Processing Record 21 of set 2 | flinders
Processing Record 22 of set 2 | hilo
Processing Record 23 of set 2 | charlottesville
Processing Record 24 of set 2 | sitka
Processing Record 25 of set 2 | constitucion
Processing Record 26 of set 2 | vila velha
Processing Record 27 of set 2 | tumannyy
City not found tumannyy
Processing Record 28 of set 2 | vaitupu
City not found vaitupu
Processing Record 29 of set 2 | attawapiskat
City not found attawapiskat
Processing Record 30 of set 2 | taolanaro
City not found taolanaro
Processing Record 31 of set 2 | otane
Processing Record 32 of set 2 | norman wells
Processing Record 33 of set 2 | butaritari
Processing Record 34 of set 2 | tasiilaq
Processing Record 35 of set 2 | petropavlivka
Processing Record 36 of set 2 | sindor
Processing Record 37 of set 2 | laguna
Processing Record 38 of set 2 | miri
Processing Record 39 of set 2 | oeiras
Processing Record 40 of set 2 | palabuhanratu
City not found palabuhanratu
Processing Record 41 of set 2 | el prat de llobregat
Processing Record 42 of set 2 | avarua
Processing Record 43 of set 2 | ondorhaan
City not found ondorhaan
Processing Record 44 of set 2 | lavrentiya
Processing Record 45 of set 2 | portland
Processing Record 46 of set 2 | aklavik
Processing Record 47 of set 2 | viedma
Processing Record 48 of set 2 | novoanninskiy
Processing Record 49 of set 2 | bima
Processing Record 50 of set 2 | grindavik
Processing Record 1 of set 3 | pacific grove
Processing Record 2 of set 3 | lucea
Processing Record 3 of set 3 | makat
Processing Record 4 of set 3 | maloy
Processing Record 5 of set 3 | trelew
Processing Record 6 of set 3 | chippewa falls
Processing Record 7 of set 3 | berlevag
Processing Record 8 of set 3 | east london
Processing Record 9 of set 3 | terenos
Processing Record 10 of set 3 | hirara
Processing Record 11 of set 3 | barroquinha
Processing Record 12 of set 3 | tuggurt
City not found tuggurt
Processing Record 13 of set 3 | nemuro
Processing Record 14 of set 3 | dawlatabad
Processing Record 15 of set 3 | kavaratti
Processing Record 16 of set 3 | tab
Processing Record 17 of set 3 | castro
Processing Record 18 of set 3 | sarangani
Processing Record 19 of set 3 | georgetown
Processing Record 20 of set 3 | san jeronimo
Processing Record 21 of set 3 | saint george
Processing Record 22 of set 3 | warrington
Processing Record 23 of set 3 | nancha
Processing Record 24 of set 3 | umm kaddadah
Processing Record 25 of set 3 | bud
Processing Record 26 of set 3 | tuktoyaktuk
Processing Record 27 of set 3 | barrow
Processing Record 28 of set 3 | wexford
Processing Record 29 of set 3 | saint-philippe
Processing Record 30 of set 3 | khovu-aksy
Processing Record 31 of set 3 | bethel
Processing Record 32 of set 3 | usoke
Processing Record 33 of set 3 | bandar-e lengeh
Processing Record 34 of set 3 | sao filipe
Processing Record 35 of set 3 | nenjiang
Processing Record 36 of set 3 | boali
Processing Record 37 of set 3 | khatanga
Processing Record 38 of set 3 | mayumba
Processing Record 39 of set 3 | axim
Processing Record 40 of set 3 | high level
Processing Record 41 of set 3 | los llanos de aridane
Processing Record 42 of set 3 | corrente
Processing Record 43 of set 3 | bonthe
Processing Record 44 of set 3 | nabire
Processing Record 45 of set 3 | horsham
Processing Record 46 of set 3 | adrar
Processing Record 47 of set 3 | naze
Processing Record 48 of set 3 | airai
Processing Record 49 of set 3 | samalaeulu
City not found samalaeulu
Processing Record 50 of set 3 | ribeira grande
Processing Record 1 of set 4 | port elizabeth
Processing Record 2 of set 4 | tiznit
Processing Record 3 of set 4 | mullaitivu
City not found mullaitivu
Processing Record 4 of set 4 | boromlya
Processing Record 5 of set 4 | bon accord
Processing Record 6 of set 4 | cayenne
Processing Record 7 of set 4 | new norfolk
Processing Record 8 of set 4 | velyka lepetykha
Processing Record 9 of set 4 | lebu
Processing Record 10 of set 4 | lompoc
Processing Record 11 of set 4 | pilar
Processing Record 12 of set 4 | lasa
Processing Record 13 of set 4 | tocopilla
Processing Record 14 of set 4 | ambilobe
Processing Record 15 of set 4 | mega
Processing Record 16 of set 4 | san cristobal
Processing Record 17 of set 4 | cherskiy
Processing Record 18 of set 4 | ndele
Processing Record 19 of set 4 | hay river
Processing Record 20 of set 4 | sakakah
Processing Record 21 of set 4 | illoqqortoormiut
City not found illoqqortoormiut
Processing Record 22 of set 4 | batagay
Processing Record 23 of set 4 | beringovskiy
Processing Record 24 of set 4 | santa cruz
Processing Record 25 of set 4 | silale
Processing Record 26 of set 4 | wanning
Processing Record 27 of set 4 | seredka
Processing Record 28 of set 4 | srednekolymsk
Processing Record 29 of set 4 | asmara
Processing Record 30 of set 4 | barentsburg
City not found barentsburg
Processing Record 31 of set 4 | broken hill
Processing Record 32 of set 4 | nanortalik
Processing Record 33 of set 4 | burkhala
City not found burkhala
Processing Record 34 of set 4 | pevek
Processing Record 35 of set 4 | salalah
Processing Record 36 of set 4 | pisco
Processing Record 37 of set 4 | grojec

Processing Record 38 of set 4 | kabanjahe
Processing Record 39 of set 4 | fairbanks
Processing Record 40 of set 4 | wewak
Processing Record 41 of set 4 | matamoros
Processing Record 42 of set 4 | provideniya
Processing Record 43 of set 4 | kastamonu
Processing Record 44 of set 4 | salym
Processing Record 45 of set 4 | port lincoln
Processing Record 46 of set 4 | necochea
Processing Record 47 of set 4 | bauchi
Processing Record 48 of set 4 | verkhniy baskunchak
Processing Record 49 of set 4 | severo-kurilsk
Processing Record 50 of set 4 | troitsko-pechorsk
Processing Record 1 of set 5 | geraldton
Processing Record 2 of set 5 | dukat
Processing Record 3 of set 5 | clyde river
Processing Record 4 of set 5 | sengiley
Processing Record 5 of set 5 | itoman
Processing Record 6 of set 5 | kodiak
Processing Record 7 of set 5 | sena madureira
Processing Record 8 of set 5 | vestmannaeyjar
Processing Record 9 of set 5 | chokurdakh
Processing Record 10 of set 5 | chuy
Processing Record 11 of set 5 | goure
Processing Record 12 of set 5 | formosa
Processing Record 13 of set 5 | yarkovo
Processing Record 14 of set 5 | katsuura
Processing Record 15 of set 5 | palafrugell
Processing Record 16 of set 5 | price
Processing Record 17 of set 5 | santa fe
Processing Record 18 of set 5 | loa janan
Processing Record 19 of set 5 | sidi ali
Processing Record 20 of set 5 | malabo
Processing Record 21 of set 5 | almaznyy
Processing Record 22 of set 5 | padang
Processing Record 23 of set 5 | aykhal
Processing Record 24 of set 5 | eydhafushi
Processing Record 25 of set 5 | abrau-dyurso
Processing Record 26 of set 5 | west bay
Processing Record 27 of set 5 | san quintin
Processing Record 28 of set 5 | amahai
Processing Record 29 of set 5 | balykshi
Processing Record 30 of set 5 | kampene
Processing Record 31 of set 5 | santa rosa
Processing Record 32 of set 5 | colares
Processing Record 33 of set 5 | kurilsk
Processing Record 34 of set 5 | saint-joseph
Processing Record 35 of set 5 | mvuma
Processing Record 36 of set 5 | quelimane
Processing Record 37 of set 5 | auburn
Processing Record 38 of set 5 | praia
Processing Record 39 of set 5 | celestun
Processing Record 40 of set 5 | leopold
Processing Record 41 of set 5 | dafeng
Processing Record 42 of set 5 | lhuntshi
City not found lhuntshi
Processing Record 43 of set 5 | muzhi
Processing Record 44 of set 5 | yatou
Processing Record 45 of set 5 | gimli
Processing Record 46 of set 5 | madinat sittah uktubar
Processing Record 47 of set 5 | tarudant
City not found tarudant
Processing Record 48 of set 5 | lagoa
Processing Record 49 of set 5 | sept-iles
Processing Record 50 of set 5 | zhigansk
Processing Record 1 of set 6 | puerto carreno
Processing Record 2 of set 6 | rauma
Processing Record 3 of set 6 | faya
Processing Record 4 of set 6 | saskylakh
Processing Record 5 of set 6 | cabo san lucas
Processing Record 6 of set 6 | lorengau
Processing Record 7 of set 6 | klaksvik
Processing Record 8 of set 6 | praia da vitoria
Processing Record 9 of set 6 | tubruq
City not found tubruq
Processing Record 10 of set 6 | saldanha
Processing Record 11 of set 6 | nyagan
Processing Record 12 of set 6 | tiksi
Processing Record 13 of set 6 | arrecife
Processing Record 14 of set 6 | twentynine palms
Processing Record 15 of set 6 | sampit
Processing Record 16 of set 6 | kloulklubed
Processing Record 17 of set 6 | adelanto
Processing Record 18 of set 6 | mondlo
Processing Record 19 of set 6 | nouadhibou
Processing Record 20 of set 6 | mogapi
Processing Record 21 of set 6 | sinjai
Processing Record 22 of set 6 | acuna
City not found acuna
Processing Record 23 of set 6 | bengkulu
Processing Record 24 of set 6 | sotuta
Processing Record 25 of set 6 | la mana
Processing Record 26 of set 6 | posse
Processing Record 27 of set 6 | faanui
Processing Record 28 of set 6 | egvekinot
Processing Record 29 of set 6 | parrita
Processing Record 30 of set 6 | tubuala
Processing Record 31 of set 6 | longyearbyen
Processing Record 32 of set 6 | verkhnyaya inta
Processing Record 33 of set 6 | korla
Processing Record 34 of set 6 | fulitun
City not found fulitun
Processing Record 35 of set 6 | olafsvik
Processing Record 36 of set 6 | erenhot
Processing Record 37 of set 6 | shenjiamen
Processing Record 38 of set 6 | ust-nera
Processing Record 39 of set 6 | hofn
Processing Record 40 of set 6 | sola
Processing Record 41 of set 6 | hadejia
Processing Record 42 of set 6 | karratha
Processing Record 43 of set 6 | jining
Processing Record 44 of set 6 | narasannapeta
Processing Record 45 of set 6 | plavsk
Processing Record 46 of set 6 | manitowoc
Processing Record 47 of set 6 | madimba
Processing Record 48 of set 6 | shipitsyno
Processing Record 49 of set 6 | pozo colorado
Processing Record 50 of set 6 | todos santos
Processing Record 1 of set 7 | leshukonskoye
Processing Record 2 of set 7 | mys shmidta
City not found mys shmidta
Processing Record 3 of set 7 | marcona
City not found marcona
Processing Record 4 of set 7 | abu dhabi
Processing Record 5 of set 7 | bargal
City not found bargal
Processing Record 6 of set 7 | jardim
Processing Record 7 of set 7 | inverness
Processing Record 8 of set 7 | aleksandrovka
Processing Record 9 of set 7 | mezen
Processing Record 10 of set 7 | labutta
City not found labutta
Processing Record 11 of set 7 | namibe
Processing Record 12 of set 7 | coihaique
Processing Record 13 of set 7 | vanavara
Processing Record 14 of set 7 | santa comba
Processing Record 15 of set 7 | dingle
Processing Record 16 of set 7 | talnakh
Processing Record 17 of set 7 | qiyang
Processing Record 18 of set 7 | talas
Processing Record 19 of set 7 | riyadh
Processing Record 20 of set 7 | sedelnikovo
City not found sedelnikovo
Processing Record 21 of set 7 | pierre
Processing Record 22 of set 7 | port moresby
Processing Record 23 of set 7 | piatra soimului
Processing Record 24 of set 7 | beian
Processing Record 25 of set 7 | camacha
Processing Record 26 of set 7 | tunduru
City not found tunduru
Processing Record 27 of set 7 | lensk
Processing Record 28 of set 7 | leningradskiy
Processing Record 29 of set 7 | kaeo
Processing Record 30 of set 7 | maceio
Processing Record 31 of set 7 | kavieng
Processing Record 32 of set 7 | chaozhou
Processing Record 33 of set 7 | clarksburg
Processing Record 34 of set 7 | san ramon
Processing Record 35 of set 7 | sechura
Processing Record 36 of set 7 | bontang
Processing Record 37 of set 7 | shieli
Processing Record 38 of set 7 | alofi
Processing Record 39 of set 7 | odweyne
Processing Record 40 of set 7 | amderma
City not found amderma
Processing Record 41 of set 7 | caldwell
Processing Record 42 of set 7 | nipawin
Processing Record 43 of set 7 | upernavik
Processing Record 44 of set 7 | bathsheba
Processing Record 45 of set 7 | codrington
Processing Record 46 of set 7 | alta gracia
Processing Record 47 of set 7 | chagda
City not found chagda
Processing Record 48 of set 7 | sorvag
City not found sorvag
Processing Record 49 of set 7 | narsaq
Processing Record 50 of set 7 | banda aceh
Processing Record 1 of set 8 | santa cruz de la palma
Processing Record 2 of set 8 | baiyin
Processing Record 3 of set 8 | pasaje
Processing Record 4 of set 8 | mabaruma
Processing Record 5 of set 8 | ancud
Processing Record 6 of set 8 | vila franca do campo
Processing Record 7 of set 8 | tautira
Processing Record 8 of set 8 | klyuchi
Processing Record 9 of set 8 | omboue
Processing Record 10 of set 8 | komsomolskiy
Processing Record 11 of set 8 | san francisco menendez
Processing Record 12 of set 8 | vardo
Processing Record 13 of set 8 | abatskoye
Processing Record 14 of set 8 | venezuela
Processing Record 15 of set 8 | taltal
Processing Record 16 of set 8 | kungurtug
Processing Record 17 of set 8 | eyl
Processing Record 18 of set 8 | shemonaikha
Processing Record 19 of set 8 | narragansett
Processing Record 20 of set 8 | imphal
Processing Record 21 of set 8 | saint-pierre
Processing Record 22 of set 8 | amapa
Processing Record 23 of set 8 | umzimvubu
City not found umzimvubu
Processing Record 24 of set 8 | bumba
Processing Record 25 of set 8 | turinsk
Processing Record 26 of set 8 | fortuna
Processing Record 27 of set 8 | yumen
Processing Record 28 of set 8 | beruwala

Processing Record 29 of set 8 | cam pha
City not found cam pha
Processing Record 30 of set 8 | tselinnoye
Processing Record 31 of set 8 | rio grande
Processing Record 32 of set 8 | nishihara
Processing Record 33 of set 8 | congonhas
Processing Record 34 of set 8 | sorland
Processing Record 35 of set 8 | zile
Processing Record 36 of set 8 | ankola
Processing Record 37 of set 8 | eureka
Processing Record 38 of set 8 | evans
Processing Record 39 of set 8 | bandarbeyla
Processing Record 40 of set 8 | wamba
Processing Record 41 of set 8 | pemba
Processing Record 42 of set 8 | banepa
Processing Record 43 of set 8 | victoria
Processing Record 44 of set 8 | kisangani
Processing Record 45 of set 8 | luderitz
Processing Record 46 of set 8 | samarai
Processing Record 47 of set 8 | pocone
Processing Record 48 of set 8 | grand river south east
City not found grand river south east
Processing Record 49 of set 8 | dryden
Processing Record 50 of set 8 | hobyo
Processing Record 1 of set 9 | la ronge
Processing Record 2 of set 9 | harper
Processing Record 3 of set 9 | itarantim
Processing Record 4 of set 9 | byron bay
Processing Record 5 of set 9 | uniontown
Processing Record 6 of set 9 | kula
Processing Record 7 of set 9 | cidreira
Processing Record 8 of set 9 | eisenberg
Processing Record 9 of set 9 | eldikan
City not found eldikan
Processing Record 10 of set 9 | verkhnyachka
Processing Record 11 of set 9 | shimoda
Processing Record 12 of set 9 | benjamin constant
Processing Record 13 of set 9 | saleaula
City not found saleaula
Processing Record 14 of set 9 | cabinda
Processing Record 15 of set 9 | san borja
Processing Record 16 of set 9 | crixas
Processing Record 17 of set 9 | ilulissat
Processing Record 18 of set 9 | zaqatala
Processing Record 19 of set 9 | thompson
Processing Record 20 of set 9 | hvammstangi
City not found hvammstangi
Processing Record 21 of set 9 | yuksekova
Processing Record 22 of set 9 | tambun
Processing Record 23 of set 9 | de aar
Processing Record 24 of set 9 | nanchong
Processing Record 25 of set 9 | ilebo
Processing Record 26 of set 9 | arandis
Processing Record 27 of set 9 | mangrol
Processing Record 28 of set 9 | suleja
Processing Record 29 of set 9 | rach gia
Processing Record 30 of set 9 | torquay
Processing Record 31 of set 9 | coahuayana
Processing Record 32 of set 9 | basse
Processing Record 33 of set 9 | colombia
Processing Record 34 of set 9 | yarada
Processing Record 35 of set 9 | yablonovo
Processing Record 36 of set 9 | calahorra
Processing Record 37 of set 9 | tucuma
Processing Record 38 of set 9 | volosovo
Processing Record 39 of set 9 | griffith
Processing Record 40 of set 9 | trincomalee
Processing Record 41 of set 9 | blackwater
Processing Record 42 of set 9 | sug-aksy
City not found sug-aksy
Processing Record 43 of set 9 | barkhan
Processing Record 44 of set 9 | hualmay
Processing Record 45 of set 9 | san carlos de bariloche
Processing Record 46 of set 9 | tezu
Processing Record 47 of set 9 | bang saphan
Processing Record 48 of set 9 | lucapa
Processing Record 49 of set 9 | yulara
Processing Record 50 of set 9 | dubbo
Processing Record 1 of set 10 | agadir
Processing Record 2 of set 10 | puri
Processing Record 3 of set 10 | bilma
Processing Record 4 of set 10 | agadez
Processing Record 5 of set 10 | la tajeada
City not found la tajeada
Processing Record 6 of set 10 | fethiye
Processing Record 7 of set 10 | melfi
Processing Record 8 of set 10 | rovaniemi
Processing Record 9 of set 10 | louisbourg
City not found louisbourg
Processing Record 10 of set 10 | flagstaff
Processing Record 11 of set 10 | pontian kecil
Processing Record 12 of set 10 | morelia
Processing Record 13 of set 10 | ormara
Processing Record 14 of set 10 | hopfgarten
Processing Record 15 of set 10 | yerbogachen
Processing Record 16 of set 10 | balakhninskiy
Processing Record 17 of set 10 | safaga
Processing Record 18 of set 10 | port macquarie
Processing Record 19 of set 10 | penzance
Processing Record 20 of set 10 | hamilton
Processing Record 21 of set 10 | gallup
Processing Record 22 of set 10 | kuytun
Processing Record 23 of set 10 | waipawa
Processing Record 24 of set 10 | mahibadhoo
Processing Record 25 of set 10 | stillwater
Processing Record 26 of set 10 | healdsburg
Processing Record 27 of set 10 | xining
Processing Record 28 of set 10 | canon city
Processing Record 29 of set 10 | kushiro
Processing Record 30 of set 10 | tilichiki
Processing Record 31 of set 10 | domoni
Processing Record 32 of set 10 | riberalta
Processing Record 33 of set 10 | kalispell
Processing Record 34 of set 10 | coolum beach
Processing Record 35 of set 10 | dzhusaly
City not found dzhusaly
Processing Record 36 of set 10 | severodvinsk
Processing Record 37 of set 10 | bolshegrivskoye
City not found bolshegrivskoye
Processing Record 38 of set 10 | puerto del rosario
Processing Record 39 of set 10 | khonuu
City not found khonuu
Processing Record 40 of set 10 | pyapon
Processing Record 41 of set 10 | ponta pora
Processing Record 42 of set 10 | antofagasta
Processing Record 43 of set 10 | danilovka
Processing Record 44 of set 10 | pangai
Processing Record 45 of set 10 | mogoytuy
Processing Record 46 of set 10 | pangnirtung
Processing Record 47 of set 10 | quatre cocos
Processing Record 48 of set 10 | vernon
Processing Record 49 of set 10 | la rioja
Processing Record 50 of set 10 | nizhneyansk
City not found nizhneyansk
Processing Record 1 of set 11 | yirol
City not found yirol
Processing Record 2 of set 11 | kostomuksha
Processing Record 3 of set 11 | half moon bay
Processing Record 4 of set 11 | horqueta
Processing Record 5 of set 11 | saint anthony
Processing Record 6 of set 11 | salumbar
Processing Record 7 of set 11 | rawson
Processing Record 8 of set 11 | mirnyy
Processing Record 9 of set 11 | sakaiminato
Processing Record 10 of set 11 | acapulco
Processing Record 11 of set 11 | baton rouge
Processing Record 12 of set 11 | cavalcante
Processing Record 13 of set 11 | lexington park
Processing Record 14 of set 11 | mitsamiouli
Processing Record 15 of set 11 | sertanopolis
Processing Record 16 of set 11 | ust-maya
Processing Record 17 of set 11 | sistranda
Processing Record 18 of set 11 | cabedelo
Processing Record 19 of set 11 | muscat
Processing Record 20 of set 11 | darhan
Processing Record 21 of set 11 | sioux lookout
Processing Record 22 of set 11 | marrakesh
Processing Record 23 of set 11 | kidal
Processing Record 24 of set 11 | payson
Processing Record 25 of set 11 | ksenyevka
City not found ksenyevka
Processing Record 26 of set 11 | miranorte
City not found miranorte
Processing Record 27 of set 11 | port keats
Processing Record 28 of set 11 | sand springs
Processing Record 29 of set 11 | krasnoselkup
Processing Record 30 of set 11 | havre-saint-pierre
Processing Record 31 of set 11 | khani
Processing Record 32 of set 11 | cairns
Processing Record 33 of set 11 | haibowan
City not found haibowan
Processing Record 34 of set 11 | kupang
Processing Record 35 of set 11 | dunedin
Processing Record 36 of set 11 | wagar
Processing Record 37 of set 11 | san onofre
Processing Record 38 of set 11 | coquimbo
Processing Record 39 of set 11 | muyezerskiy
Processing Record 40 of set 11 | keflavik
Processing Record 41 of set 11 | panorama
Processing Record 42 of set 11 | mao
Processing Record 43 of set 11 | anloga
Processing Record 44 of set 11 | okhotsk
Processing Record 45 of set 11 | porto novo
Processing Record 46 of set 11 | kapit
Processing Record 47 of set 11 | tsuruoka
Processing Record 48 of set 11 | ouadda
Processing Record 49 of set 11 | hargeysa
Processing Record 50 of set 11 | saint-francois
Processing Record 1 of set 12 | esso
Processing Record 2 of set 12 | dakar
Processing Record 3 of set 12 | irbil
Processing Record 4 of set 12 | tabas
Processing Record 5 of set 12 | morros
Processing Record 6 of set 12 | karatau
Processing Record 7 of set 12 | tevriz
Processing Record 8 of set 12 | cochrane
Processing Record 9 of set 12 | vestmanna
Processing Record 10 of set 12 | bonavista
Processing Record 11 of set 12 | north battleford
Processing Record 12 of set 12 | evensk
Processing Record 13 of set 12 | tazovskiy
Processing Record 14 of set 12 | clarence town
Processing Record 15 of set 12 | gualeguay

Processing Record 16 of set 12 | ghanzi
Processing Record 17 of set 12 | winnemucca
Processing Record 18 of set 12 | hukuntsi
Processing Record 19 of set 12 | yuncheng
Processing Record 20 of set 12 | larsnes
Processing Record 21 of set 12 | nave
Processing Record 22 of set 12 | tabulbah
City not found tabulbah
Processing Record 23 of set 12 | abha
Processing Record 24 of set 12 | labuhan
Processing Record 25 of set 12 | tikrit
Processing Record 26 of set 12 | oktyabrskiy
Processing Record 27 of set 12 | mandurah
Processing Record 28 of set 12 | belyy yar
Processing Record 29 of set 12 | matadi
Processing Record 30 of set 12 | tsienyane
City not found tsienyane
Processing Record 31 of set 12 | talara
Processing Record 32 of set 12 | durban
Processing Record 33 of set 12 | giraltovce
Processing Record 34 of set 12 | ostrovnoy
Processing Record 35 of set 12 | gizo
Processing Record 36 of set 12 | sala consilina
Processing Record 37 of set 12 | mount isa
Processing Record 38 of set 12 | januaria
Processing Record 39 of set 12 | kayerkan
Processing Record 40 of set 12 | fuengirola
Processing Record 41 of set 12 | ryugasaki
Processing Record 42 of set 12 | opuwo
Processing Record 43 of set 12 | souillac
Processing Record 44 of set 12 | cartagena
Processing Record 45 of set 12 | tuatapere
Processing Record 46 of set 12 | roald
________________________
Data Retrieval Completed
________________________

In [10]:
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Clouldiness,Wind Speed,Country,Date
0,Bredasdorp,-34.5322,20.0403,60.49,80,56,6.87,ZA,2022-11-14 05:21:05
1,Hami,42.8000,93.4500,44.22,30,2,2.04,CN,2022-11-14 05:21:05
2,Busselton,-33.6500,115.3333,71.06,33,0,2.53,AU,2022-11-14 05:21:05
3,Buraydah,26.3260,43.9750,66.65,34,3,5.46,SA,2022-11-14 05:18:10
4,Nome,64.5011,-165.4064,17.67,67,0,0.00,US,2022-11-14 05:21:06
5,Yellowknife,62.4560,-114.3525,23.52,93,75,11.50,CA,2022-11-14 05:21:06
6,Vuktyl,63.8567,57.3094,13.08,95,100,5.48,RU,2022-11-14 05:21:06
7,Nikolskoye,59.7035,30.7861,32.81,86,27,2.13,RU,2022-11-14 05:21:06
8,Carnarvon,-24.8667,113.6333,83.59,36,0,12.28,AU,2022-11-14 05:21:07
9,Esperance,-33.8667,121.9000,61.48,57,32,12.26,AU,2022-11-14 05:21:07

In [11]:
city_data_df = city_data_df[['City','Country','Date','Lat','Lng','Max Temp','Humidity','Clouldiness','Wind Speed']]
city_data_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Clouldiness,Wind Speed
0,Bredasdorp,ZA,2022-11-14 05:21:05,-34.5322,20.0403,60.49,80,56,6.87
1,Hami,CN,2022-11-14 05:21:05,42.8000,93.4500,44.22,30,2,2.04
2,Busselton,AU,2022-11-14 05:21:05,-33.6500,115.3333,71.06,33,0,2.53
3,Buraydah,SA,2022-11-14 05:18:10,26.3260,43.9750,66.65,34,3,5.46
4,Nome,US,2022-11-14 05:21:06,64.5011,-165.4064,17.67,67,0,0.00
...,...,...,...,...,...,...,...,...,...
541,Opuwo,NA,2022-11-14 05:30:34,-18.0607,13.8400,72.14,21,1,0.45
542,Souillac,MU,2022-11-14 05:34:13,-20.5167,57.5167,70.18,94,75,2.30
543,Cartagena,CO,2022-11-14 05:33:12,10.3997,-75.5144,78.42,94,40,2.30
544,Tuatapere,NZ,2022-11-14 05:34:13,-46.1333,167.6833,66.43,58,65,0.76
545,Roald,NO,2022-11-14 05:34:13,62.5833,6.1333,53.17,81,0,6.91

In [12]:
#  create the output file (CSV)

output_data_file = "weather_data/cities.csv"

# export the data

city_data_df.to_csv(output_data_file, index_label = "City_ID")

In [13]:
# Etract data for scatter plot

lats = city_data_df["Lat"]
max_temps = city_data_df["Max Temp"]
humidity = city_data_df["Humidity"]
cloudiness = city_data_df["Clouldiness"]
wind_speed = city_data_df["Wind Speed"]

In [192]:
# import time module
import time
%matplotlib
import matplotlib.pyplot as plt
%matplotlib qt


# build the scatter plot for latitudes vs max. temp.

plt.scatter(lats, max_temps,
           edgecolor="black",
           linewidths=1, marker="o",
           alpha =0.8, label="Cities")


# add additional properties

plt.title(f"City Latitudes Vs. Maximum Temperature "+ time.strftime("%x"))
plt.ylabel("Maximum Temperature (F)")
plt.xlabel("Latitude")
plt.grid(True)

# save the figure.

plt.savefig("weather_data/Scatter_lat_Vs_maxtemp.png")

# Show plot

plt.show()

Using matplotlib backend: QtAgg

In [109]:
# build the scatter plot for latitudes vs Humidity.
%matplotlib qt

plt.scatter(lats, humidity,
           edgecolor="black",
           linewidths=1, marker="o",
           alpha =0.8, label="Cities")


# add additional properties

plt.title(f"City Latitudes Vs. Humidity (%)"+ time.strftime("%x"))
plt.ylabel("Humidity (%)")
plt.xlabel("Latitude")
plt.grid(True)

# save the figure.

plt.savefig("weather_data/Scatter_lat_Vs_humidity.png")

# Show plot
plt.show()

In [17]:
# build the scatter plot for latitudes vs Cloudiness.

plt.scatter(lats, cloudiness,
           edgecolor="black",
           linewidths=1, marker="o",
           alpha =0.8, label="Cities")


# add additional properties

plt.title(f"City Latitudes Vs. Cloudiness(%) "+ time.strftime("%x"))
plt.ylabel("Cloudiness (%)")
plt.xlabel("Latitude")
plt.grid(True)

# save the figure.

plt.savefig("weather_data/Scatter_lat_Vs_cloudiness.png")

# Show plot
plt.show()

In [18]:
# build the scatter plot for latitudes vs Wind Speed.

plt.scatter(lats, wind_speed,
           edgecolor="black",
           linewidths=1, marker="o",
           alpha =0.8, label="Cities")


# add additional properties

plt.title(f"City Latitudes Vs. Wind Speed "+ time.strftime("%x"))
plt.ylabel("Wind Speed (mph)")
plt.xlabel("Latitude")
plt.grid(True)

# save the figure.

plt.savefig("weather_data/Scatter_lat_Vs_windspeed.png")

# Show plot
plt.show()
plt.tight_layout()

In [180]:
# import linear regression from te SciPy stats module.

import matplotlib.pyplot as plt
from scipy.stats import linregress

# create a function to perform linear regression on the weather data
# plot the regression line with equation

def plot_linear_regression(x_values, y_values, title, y_label, text_coordinates):
    
   # perform linear regression

    (slope, intercept, r_value, p_value, std_err) = linregress(x_values, y_values)
    
    #calcualte y value from regression
    
    regress_values = x_values * slope + intercept
    
    # the line equation
    
    line_eq = "y =" + str(round(slope,2)) + "x +" + str(round(intercept,2))
    
    # Create a scatter plot and plot the regression line.
    plt.scatter(x_values,y_values)
    plt.rcParams["figure.figsize"] = (10,6)
   
    
    plt.plot(x_values,regress_values,"r")
        
    # Annotate the text for the line equation.
    plt.annotate(line_eq, text_coordinates, fontsize=15, color="red")
    
    plt.title(title)
    plt.xlabel('Latitude')
    plt.ylabel(y_label)
    
    plt.show()

In [181]:
# extract the north hemispher data

north_hemi_df = city_data_df.loc[(city_data_df['Lat']>=0)]
north_hemi_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Clouldiness,Wind Speed
1,Hami,CN,2022-11-14 05:21:05,42.8000,93.4500,44.22,30,2,2.04
3,Buraydah,SA,2022-11-14 05:18:10,26.3260,43.9750,66.65,34,3,5.46
4,Nome,US,2022-11-14 05:21:06,64.5011,-165.4064,17.67,67,0,0.00
5,Yellowknife,CA,2022-11-14 05:21:06,62.4560,-114.3525,23.52,93,75,11.50
6,Vuktyl,RU,2022-11-14 05:21:06,63.8567,57.3094,13.08,95,100,5.48
...,...,...,...,...,...,...,...,...,...
538,Kayerkan,RU,2022-11-14 05:34:12,69.3497,87.7602,-20.83,81,13,3.22
539,Fuengirola,ES,2022-11-14 05:34:12,36.5400,-4.6247,61.84,94,20,6.91
540,Ryugasaki,JP,2022-11-14 05:34:12,35.9000,140.1833,65.05,44,100,7.56
543,Cartagena,CO,2022-11-14 05:33:12,10.3997,-75.5144,78.42,94,40,2.30
545,Roald,NO,2022-11-14 05:34:13,62.5833,6.1333,53.17,81,0,6.91

In [182]:
# extract the north hemispher data

south_hemi_df = city_data_df.loc[(city_data_df['Lat']<0)]
south_hemi_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Clouldiness,Wind Speed
0,Bredasdorp,ZA,2022-11-14 05:21:05,-34.5322,20.0403,60.49,80,56,6.87
2,Busselton,AU,2022-11-14 05:21:05,-33.6500,115.3333,71.06,33,0,2.53
8,Carnarvon,AU,2022-11-14 05:21:07,-24.8667,113.6333,83.59,36,0,12.28
9,Esperance,AU,2022-11-14 05:21:07,-33.8667,121.9000,61.48,57,32,12.26
10,Puerto Ayora,EC,2022-11-14 05:21:07,-0.7393,-90.3518,69.55,84,61,5.99
...,...,...,...,...,...,...,...,...,...
536,Mount Isa,AU,2022-11-14 05:31:23,-20.7333,139.5000,92.97,43,40,12.66
537,Januaria,BR,2022-11-14 05:34:12,-15.4833,-44.3667,69.69,92,67,2.46
541,Opuwo,NA,2022-11-14 05:30:34,-18.0607,13.8400,72.14,21,1,0.45
542,Souillac,MU,2022-11-14 05:34:13,-20.5167,57.5167,70.18,94,75,2.30
544,Tuatapere,NZ,2022-11-14 05:34:13,-46.1333,167.6833,66.43,58,65,0.76

In [183]:
import matplotlib.pyplot as plt

# Linear regaression on the northern hemisphere

x_values = north_hemi_df["Lat"]
y_values = north_hemi_df["Max Temp"]

# call the function


plot_linear_regression(x_values, y_values,
                       'Linear Regression on the northern Hemisphere for maximum temperatue', 
                       'Max Temp', (10,-20))

plt.savefig("weather_data/Scatter_northlat_Vs_maxtemp_regression.png")

In [184]:
import matplotlib.pyplot as plt

# Linear regaression on the southern hemisphere

x_values = south_hemi_df["Lat"]
y_values = south_hemi_df["Max Temp"]

# call the function
plot_linear_regression(x_values, y_values,
                       'Linear Regression on the southern Hemisphere for maximum temperatue', 
                       'Max Temp', (-55,90))

plt.savefig("weather_data/Scatter_southlat_Vs_maxtemp_regression.png")

In [185]:
# Linear regaression on the northern hemisphere

x_values = north_hemi_df["Lat"]
y_values = north_hemi_df["Humidity"]

# call the function


plot_linear_regression(x_values, y_values,
                       'Linear Regression on the northern Hemisphere for % Humidity', 
                       '% Humidity', (50,10))

plt.savefig("weather_data/Scatter_northlat_Vs_Humidity_regression.png")

In [186]:
# Linear regaression on the southern hemisphere

x_values = south_hemi_df["Lat"]
y_values = south_hemi_df["Humidity"]

# call the function
plot_linear_regression(x_values, y_values,
                       'Linear Regression on the southern Hemisphere for % Humidity', 
                       '% Humidity', (-50,20))

plt.savefig("weather_data/Scatter_southlat_Vs_Humidity_regression.png")

In [187]:
# Linear regaression on the northern hemisphere for cloudiness

x_values = north_hemi_df["Lat"]
y_values = north_hemi_df["Clouldiness"]

# call the function


plot_linear_regression(x_values, y_values,
                       'Linear Regression on the northern Hemisphere for % Clouldiness', 
                       '% Clouldiness', (0,3))

plt.savefig("weather_data/Scatter_northlat_Vs_Clouldiness_regression.png")

In [191]:
# Linear regaression on the southern hemisphere for Clouldiness

%matplotlib qt

x_values = south_hemi_df["Lat"]
y_values = south_hemi_df["Clouldiness"]

# call the function
plot_linear_regression(x_values, y_values,
                       'Linear Regression on the southern Hemisphere for % Clouldiness', 
                       '% Clouldiness', (-50,10))

plt.savefig("weather_data/Scatter_southlat_Vs_Clouldiness_regression.png")